addons:
    code_climate:
        repo_token: adfaf43f60becf8da1543fbc1c952b109470251fba943290bbbc4b4394dc9c84
        
language: ruby
rvm:
  - "2.2.3"

# make Travis use its legacy infrastructure
sudo: true

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rake lang:update

install: ./script/travis_setup

before_script:
  - rake db:schema:load
  - rake db:fixtures:load
  - rake lang:update
